### ISSUE TITLE
変更要望

### ISSUE THREAD

**Issue by satorope** [tetradice/scoop-iyokan-jp#2]
毎度重宝させていただいてます。
いくつか変更要望を書かせていただきます。
お手すきの際に検討していただきたく。
よろしくお願いします。

- putty-ranvis
通常のPuttyと同じくplinkやpscpなど、EXE全部にshimlinkを作っていただきたく。

- persistの追加
バージョンアップ時にプラグインなど引き継いでほしいです。
私は以下のを使ってるので、それをまずご検討ください。

  - mery Pluginsフォルダ
公式HPにいくつかあり、それをインストールしています

  - winmerge-jp MergePluginsフォルダ
実際のところはxdocdiff Plugin対策なので、xdoc2txt.exeも対象となるでしょうけど。またこれは別に。
32bit http://freemind.s57.xrea.com/xdocdiffPlugin/en/index.html
64bit http://crus.mydns.jp/xdocdiffPlugin64/

**Comment by tetradice** [comment]
@satorope すみません、対応がたいへん遅くなりました。
それぞれ対応しましたため、`scoop update` を実行して確認していただけますよう、よろしくお願いします。
