### ISSUE TITLE
追加要望

### ISSUE THREAD

**Issue by satorope** [tetradice/scoop-iyokan-jp#3]
続きまして、以下の追加を検討お願いします。

- mery ベータ版
最新版は今まで通りベータ扱いのようですので

- xdoc2txt
http://ebstudio.info/home/xdoc2txt.html
どちらかというとWinmergeのxdocdiffPlugin用に、xdoc2txt.exeのパスを通すための案です。

- ctags日本語版
http://hp.vector.co.jp/authors/VA025040/

**Comment by tetradice** [comment]
ご要望ありがとうございます :smile:

> * mery ベータ版
> * ctags日本語版

それぞれ追加しました。
下記のコマンドでインストールすることができます。

```
> scoop update
> scoop install mery-beta
> scoop install exuberantctags-jp
```

※Mery ベータ版をインストールすると、コマンドラインから`mery`と入力して実行した際に
常にベータ版が起動するようになります。
正式版が起動する状態に戻したい場合は、下記コマンドを実行してください。

```
> scoop reset mery
```

> * xdoc2txt

こちらに関しては、再配布の条件がやや厳しいため、収録は見送らせていただきました。
ご了承ください。
（Scoop Bucketへの登録が「再配布」にあたるのかどうかは微妙なところなのですが……）
