### ISSUE TITLE
Meryがインストールできない

### ISSUE THREAD

**Issue by cozyatg** [tetradice/scoop-iyokan-jp#5]
こんにちは、いつも便利に利用させていただいています。

現在 Mery のインストールができない状態になっているようです。
```
> scoop install mery
Installing 'mery' (2.6.7) [64bit]
リモート サーバーがエラーを返しました: (404) 見つかりません
URL http://download.haijin-boys.com/download/Mery-x64-2.6.7.zip is not valid
```

Meryのオフィシャルサイトを確認すると、haijin-boys ドメインのダウンロードリンクはありませんが、Vectorのダウンロードリンクがあるので、ここを差し替えていただければ修正できるのでは？とおもいます。
https://www.haijin-boys.com/wiki/%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8

（自分で確認・修正してPR送ればよいのでしょうが、私自身が開発者でないためお作法から外れてはいけないかと危惧して、Issueとして挙げさせていただきました）

**Comment by tetradice** [comment]
@cozyatg 
ご報告ありがとうございます。助かりました 👍 
ご提案いただきましたとおり、ダウンロード先URLをVectorのものに変更し、正しくインストールできるようになりましたため、ご確認をよろしくお願いします。

**Comment by cozyatg** [comment]
@tetradice 
返信遅くなりましたが、本日またセットアップの機会があり、meryのインストールも無事成功しましたこと、確認できました。この度は、ご対応いただきまして、ありがとうございました。
